package me.afterdarkness.moloch.module.modules.client;

import net.spartanb312.base.core.setting.Setting;
import net.spartanb312.base.common.annotations.ModuleInfo;
import net.spartanb312.base.common.annotations.Parallel;
import net.spartanb312.base.module.Category;
import net.spartanb312.base.module.Module;
import me.afterdarkness.moloch.core.common.Color;

@Parallel(runnable = true)
@ModuleInfo(name = "MoreClickGUI", category = Category.CLIENT, description = "I ran out of fucking space in clickgui it won't compile")
public class MoreClickGUI extends Module {

    public static MoreClickGUI instance;
    public MoreClickGUI() {
        instance = this;
    }

    Setting<Page> page = setting("Page", Page.Description);

    public Setting<DescriptionMode> descriptionMode = setting("DescriptionMode", DescriptionMode.Hub).des("Description Mode").whenAtMode(page, Page.Description);
    public Setting<Boolean> descriptionModeHubExpandUp = setting("DesHubExpandUp", false).des("Description Mode Hub Expand Upwards").when(() -> descriptionMode.getValue() == DescriptionMode.Hub).whenAtMode(page, Page.Description);
    public Setting<DescriptionModeHubPage> descriptionModeHubPage = setting("DescriptionHubPage", DescriptionModeHubPage.Bar).when(() -> descriptionMode.getValue() == DescriptionMode.Hub).whenAtMode(page, Page.Description);
    public Setting<Integer> descriptionModeHubLength = setting("DescriptionHubLength", 149, 20, 300).des("Description Mode Hub Length").when(() -> descriptionMode.getValue() == DescriptionMode.Hub).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Rect).whenAtMode(page, Page.Description);
    public Setting<Integer> descriptionModeHubInitialHeight = setting("DesHubStartHeight", 34, 0, 100).des("Description Mode Hub Initial Height").when(() -> descriptionMode.getValue() == DescriptionMode.Hub).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Rect).whenAtMode(page, Page.Description);
    public Setting<Integer> descriptionModeHubHeightBetweenRowsOfText = setting("DesHubRowHeight", 1, 0, 10).des("Description Mode Hub Height Between Rows Of Text").when(() -> descriptionMode.getValue() == DescriptionMode.Hub).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Rect).whenAtMode(page, Page.Description);
    public Setting<Boolean> descriptionModeHubRounded = setting("DescriptionHubRound", false).des("Description Mode Hub Rounded").when(() -> descriptionMode.getValue() == DescriptionMode.Hub).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Rect).whenAtMode(page, Page.Description);
    public Setting<Float> descriptionModeHubRoundedRadius = setting("DesHubCornerRadius", 0.5f, 0.0f, 1.0f).des("Description Mode Hub Rounded Corner Radius").whenTrue(descriptionModeHubRounded).when(() -> descriptionMode.getValue() == DescriptionMode.Hub).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Rect).whenAtMode(page, Page.Description);
    public Setting<Boolean> descriptionModeHubRoundedTopRight = setting("DesHubRoundedTopRight", true).des("Description Mode Hub Rounded Top Right").whenTrue(descriptionModeHubRounded).when(() -> descriptionMode.getValue() == DescriptionMode.Hub).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Rect).whenAtMode(page, Page.Description);
    public Setting<Boolean> descriptionModeHubRoundedTopLeft = setting("DesHubRoundedTopLeft", true).des("Description Mode Hub Rounded Top Left").whenTrue(descriptionModeHubRounded).when(() -> descriptionMode.getValue() == DescriptionMode.Hub).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Rect).whenAtMode(page, Page.Description);
    public Setting<Boolean> descriptionModeHubRoundedBottomRight = setting("DesHubRoundedDownRight", true).des("Description Mode Hub Rounded Bottom Right").whenTrue(descriptionModeHubRounded).when(() -> descriptionMode.getValue() == DescriptionMode.Hub).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Rect).whenAtMode(page, Page.Description);
    public Setting<Boolean> descriptionModeHubRoundedBottomLeft = setting("DesHubRoundedDownLeft", true).des("Description Mode Hub Rounded Bottom Left").whenTrue(descriptionModeHubRounded).when(() -> descriptionMode.getValue() == DescriptionMode.Hub).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Rect).whenAtMode(page, Page.Description);
    public Setting<Boolean> descriptionModeHubAnimation = setting("DescriptionHubAnimate", true).des("Description Mode Hub Animate On Height Difference").when(() -> descriptionMode.getValue() == DescriptionMode.Hub).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Rect).whenAtMode(page, Page.Description);
    public Setting<Float> descriptionModeHubAnimationSpeed = setting("DesHubAnimateSpeed", 8.0f, 1.0f, 10.0f).des("Description Mode Hub Animate On Height Difference Speed").whenTrue(descriptionModeHubAnimation).when(() -> descriptionMode.getValue() == DescriptionMode.Hub).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Rect).whenAtMode(page, Page.Description);
    public Setting<Color> descriptionModeHubColor = setting("DesHubColor", new Color(new java.awt.Color(0, 0, 0, 168).getRGB())).des("Description Mode Hub Color").when(() -> descriptionMode.getValue() == DescriptionMode.Hub).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Rect).whenAtMode(page, Page.Description);
    public Setting<Boolean> descriptionModeHubOutline = setting("DesHubOutline", false).des("Description Mode Hub Outline").when(() -> descriptionMode.getValue() == DescriptionMode.Hub).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Outline).whenAtMode(page, Page.Description);
    public Setting<Float> descriptionModeHubOutlineWidth = setting("DesHubOutlineWidth", 1.0f, 1.0f, 2.0f).des("Description Mode Hub Outline Width").whenTrue(descriptionModeHubOutline).when(() -> descriptionMode.getValue() == DescriptionMode.Hub).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Outline).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Outline).whenAtMode(page, Page.Description);
    public Setting<Color> descriptionModeHubOutlineColor = setting("DesHubOutlineColor", new Color(new java.awt.Color(120, 40, 255, 255).getRGB())).des("Description Mode Hub Outline Color").whenTrue(descriptionModeHubOutline).when(() -> descriptionMode.getValue() == DescriptionMode.Hub).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Outline).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Outline).whenAtMode(page, Page.Description);

    public Setting<Boolean> descriptionModeHubHeaderText = setting("DesHubHeadText", true).des("Description Mode Hub 'Description' Text").when(() -> descriptionMode.getValue() == DescriptionMode.Hub).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Text).whenAtMode(page, Page.Description);
    public Setting<DescriptionModeHubDesTextFont> descriptionModeHubDesTextFont = setting("DesHubHeadTextFont", DescriptionModeHubDesTextFont.Objectivity).des("Description Mode Hub 'Description' Text Font").whenTrue(descriptionModeHubHeaderText).when(() -> descriptionMode.getValue() == DescriptionMode.Hub).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Text).whenAtMode(page, Page.Description);
    public Setting<Boolean> descriptionModeHubDesTextShadow = setting("DesHubHeadTextShadow", false).des("Description Mode Hub 'Description' Text Shadow").whenTrue(descriptionModeHubHeaderText).when(() -> descriptionMode.getValue() == DescriptionMode.Hub).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Text).whenAtMode(page, Page.Description);
    public Setting<Float> descriptionModeHubHeaderTextSize = setting("DesHubHeadTextSize", 1.0f, 0.1f, 3.0f).des("Description Mode Hub 'Description' Text Size").whenTrue(descriptionModeHubHeaderText).when(() -> descriptionMode.getValue() == DescriptionMode.Hub).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Text).whenAtMode(page, Page.Description);
    public Setting<Integer> descriptionModeHubHeaderTextXOffset = setting("DesHubHeadTextX", 39, -50, 50).des("Description Mode Hub 'Description' Text X Offset").whenTrue(descriptionModeHubHeaderText).when(() -> descriptionMode.getValue() == DescriptionMode.Hub).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Text).whenAtMode(page, Page.Description);
    public Setting<Integer> descriptionModeHubHeaderTextYOffset = setting("DesHubHeadTextY", 1, -50, 50).des("Description Mode Hub 'Description' Text Y Offset").whenTrue(descriptionModeHubHeaderText).when(() -> descriptionMode.getValue() == DescriptionMode.Hub).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Text).whenAtMode(page, Page.Description);
    public Setting<Color> descriptionModeHubHeaderTextColor = setting("DesHubHeadTextColor", new Color(new java.awt.Color(255, 255, 255, 255).getRGB())).des("Description Mode Hub 'Description' Text Color").whenTrue(descriptionModeHubHeaderText).when(() -> descriptionMode.getValue() == DescriptionMode.Hub).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Text).whenAtMode(page, Page.Description);
    public Setting<Boolean> descriptionModeHubIcon = setting("DescriptionHubIcon", true).des("Description Mode Hub Icon").when(() -> descriptionMode.getValue() == DescriptionMode.Hub).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Text).whenAtMode(page, Page.Description);
    public Setting<Float> descriptionModeHubIconSize = setting("DesHubIconSize", 0.9f, 0.1f, 3.0f).des("Description Mode Hub Icon Size").whenTrue(descriptionModeHubIcon).when(() -> descriptionMode.getValue() == DescriptionMode.Hub).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Text).whenAtMode(page, Page.Description);
    public Setting<Integer> descriptionModeHubIconXOffset = setting("DesHubIconX", 5, -50, 50).des("Description Mode Hub Icon X Offset").whenTrue(descriptionModeHubIcon).when(() -> descriptionMode.getValue() == DescriptionMode.Hub).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Text).whenAtMode(page, Page.Description);
    public Setting<Integer> descriptionModeHubIconYOffset = setting("DesHubIconY", -1, -50, 50).des("Description Mode Hub Icon Y Offset").whenTrue(descriptionModeHubIcon).when(() -> descriptionMode.getValue() == DescriptionMode.Hub).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Text).whenAtMode(page, Page.Description);
    public Setting<Color> descriptionModeHubIconColor = setting("DesHubIconColor", new Color(new java.awt.Color(255, 255, 255, 200).getRGB())).des("Description Mode Hub Icon Color").whenTrue(descriptionModeHubIcon).when(() -> descriptionMode.getValue() == DescriptionMode.Hub).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Text).whenAtMode(page, Page.Description);
    public Setting<DescriptionModeHubDesTextFont> descriptionModeHubDescriptionFont = setting("DesHubDesTextFont", DescriptionModeHubDesTextFont.Comfortaa).des("Description Mode Hub Description Text Font").when(() -> descriptionMode.getValue() == DescriptionMode.Hub).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Text).whenAtMode(page, Page.Description);
    public Setting<Boolean> descriptionModeHubDescriptionShadow = setting("DesHubDesTextShadow", false).des("Description Mode Hub Description Text Shadow").when(() -> descriptionMode.getValue() == DescriptionMode.Hub).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Text).whenAtMode(page, Page.Description);
    public Setting<Float> descriptionModeHubDescriptionSize = setting("DesHubDesTextSize", 1.0f, 0.1f, 3.0f).des("Description Mode Hub Size Of Description Text").when(() -> descriptionMode.getValue() == DescriptionMode.Hub).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Text).whenAtMode(page, Page.Description);
    public Setting<Boolean> descriptionModeHubDescriptionAnimation = setting("DesHubDesAnimation", true).des("Description Mode Hub Description Text Animation On Change Text").when(() -> descriptionMode.getValue() == DescriptionMode.Hub).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Text).whenAtMode(page, Page.Description);
    public Setting<Float> descriptionModeHubDescriptionAnimationSpeed = setting("DesHubDesAnimateSpeed", 4.0f, 1.0f, 10.0f).des("Description Mode Hub Description Text Animation On Change Text Speed").whenTrue(descriptionModeHubDescriptionAnimation).when(() -> descriptionMode.getValue() == DescriptionMode.Hub).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Text).whenAtMode(page, Page.Description);
    public Setting<Integer> descriptionModeHubDescriptionXOffset = setting("DesHubDesTextX", 4, 0, 50).des("Description Mode Hub Description Text X Offset").when(() -> descriptionMode.getValue() == DescriptionMode.Hub).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Text).whenAtMode(page, Page.Description);
    public Setting<Integer> descriptionModeHubDescriptionXBoundingOffset = setting("DesHubDesTextFarX", 4, 0, 50).des("Description Mode Hub Description Text X Ending Offset").when(() -> descriptionMode.getValue() == DescriptionMode.Hub).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Text).whenAtMode(page, Page.Description);
    public Setting<Integer> descriptionModeHubDescriptionYOffset = setting("DesHubDesTextY", 10, -30, 30).des("Description Mode Hub Description Text Y Offset").when(() -> descriptionMode.getValue() == DescriptionMode.Hub).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Text).whenAtMode(page, Page.Description);
    public Setting<Color> descriptionModeHubDescriptionColor = setting("DesHubDesTextColor", new Color(new java.awt.Color(200, 200, 200, 200).getRGB())).des("Description Mode Hub Description Text Color").when(() -> descriptionMode.getValue() == DescriptionMode.Hub).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Text).whenAtMode(page, Page.Description);

    public Setting<Boolean> descriptionModeHubShadow = setting("DescriptionHubShadow", true).des("Description Mode Hub Gradient Shadow").when(() -> descriptionMode.getValue() == DescriptionMode.Hub).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Shadow).whenAtMode(page, Page.Description);
    public Setting<Boolean> descriptionModeHubShadowCenterRect = setting("DesHubShadowCenterRect", false).des("Description Mode Hub Gradient Shadow Center Rect").whenTrue(descriptionModeHubShadow).when(() -> descriptionMode.getValue() == DescriptionMode.Hub).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Shadow).whenAtMode(page, Page.Description);
    public Setting<Float> descriptionModeHubShadowSize = setting("DesHubShadowSize", 0.1f, 0.0f, 1.0f).des("Description Mode Hub Gradient Shadow Size").whenTrue(descriptionModeHubShadow).when(() -> descriptionMode.getValue() == DescriptionMode.Hub).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Shadow).whenAtMode(page, Page.Description);
    public Setting<Integer> descriptionModeHubShadowAlpha = setting("DesHubShadowAlpha", 129, 0, 255).des("Description Mode Hub Gradient Shadow Alpha").whenTrue(descriptionModeHubShadow).when(() -> descriptionMode.getValue() == DescriptionMode.Hub).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Shadow).whenAtMode(page, Page.Description);

    public Setting<Boolean> descriptionModeHubBar = setting("DescriptionHubBar", true).des("Description Mode Hub Color Bar").when(() -> descriptionMode.getValue() == DescriptionMode.Hub).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Bar).whenAtMode(page, Page.Description);
    public Setting<DescriptionModeHubBarPage> descriptionModeHubBarPage = setting("DesHubBarPage", DescriptionModeHubBarPage.Glow).when(() -> descriptionMode.getValue() == DescriptionMode.Hub && descriptionModeHubBar.getValue()).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Bar).whenAtMode(page, Page.Description);
    public Setting<Float> descriptionModeHubBarHeight = setting("DescriptionHubBarHeight", 16.7f, 0.0f, 30.0f).des("Description Mode Hub Color Bar Width").when(() -> descriptionMode.getValue() == DescriptionMode.Hub && descriptionModeHubBar.getValue()).whenAtMode(descriptionModeHubBarPage, DescriptionModeHubBarPage.Base).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Bar).whenAtMode(page, Page.Description);
    public Setting<Boolean> descriptionModeHubBarRound = setting("DesHubBarRound", true).des("Description Mode Hub Color Bar Rounded").when(() -> descriptionMode.getValue() == DescriptionMode.Hub && descriptionModeHubBar.getValue()).whenAtMode(descriptionModeHubBarPage, DescriptionModeHubBarPage.Base).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Bar).whenAtMode(page, Page.Description);
    public Setting<Float> descriptionModeHubBarRoundRadius = setting("DesHubBarCornerRadius", 0.7f, 0.0f, 1.0f).des("Description Mode Hub Color Bar Rounded Corner Radius").whenTrue(descriptionModeHubBarRound).when(() -> descriptionMode.getValue() == DescriptionMode.Hub && descriptionModeHubBar.getValue()).whenAtMode(descriptionModeHubBarPage, DescriptionModeHubBarPage.Base).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Bar).whenAtMode(page, Page.Description);
    public Setting<Boolean> descriptionModeHubBarRoundTopRight = setting("DesHubBarRoundTopRight", true).des("Description Mode Hub Color Bar Rounded Top Right").whenTrue(descriptionModeHubBarRound).when(() -> descriptionMode.getValue() == DescriptionMode.Hub && descriptionModeHubBar.getValue()).whenAtMode(descriptionModeHubBarPage, DescriptionModeHubBarPage.Base).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Bar).whenAtMode(page, Page.Description);
    public Setting<Boolean> descriptionModeHubBarRoundTopLeft = setting("DesHubBarRoundTopLeft", true).des("Description Mode Hub Color Bar Rounded Top Left").whenTrue(descriptionModeHubBarRound).when(() -> descriptionMode.getValue() == DescriptionMode.Hub && descriptionModeHubBar.getValue()).whenAtMode(descriptionModeHubBarPage, DescriptionModeHubBarPage.Base).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Bar).whenAtMode(page, Page.Description);
    public Setting<Boolean> descriptionModeHubBarRoundBottomRight = setting("DesHubBarRoundDownRight", false).des("Description Mode Hub Color Bar Rounded Bottom Right").whenTrue(descriptionModeHubBarRound).when(() -> descriptionMode.getValue() == DescriptionMode.Hub && descriptionModeHubBar.getValue()).whenAtMode(descriptionModeHubBarPage, DescriptionModeHubBarPage.Base).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Bar).whenAtMode(page, Page.Description);
    public Setting<Boolean> descriptionModeHubBarRoundBottomLeft = setting("DesHubBarRoundBottomLeft", false).des("Description Mode Hub Color Bar Rounded Bottom Left").whenTrue(descriptionModeHubBarRound).when(() -> descriptionMode.getValue() == DescriptionMode.Hub && descriptionModeHubBar.getValue()).whenAtMode(descriptionModeHubBarPage, DescriptionModeHubBarPage.Base).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Bar).whenAtMode(page, Page.Description);
    public Setting<Color> descriptionModeHubBarColor = setting("DesHubBarColor", new Color(new java.awt.Color(69, 0, 178, 255).getRGB())).des("Description Hub Bar Color").when(() -> descriptionMode.getValue() == DescriptionMode.Hub && descriptionModeHubBar.getValue()).whenAtMode(descriptionModeHubBarPage, DescriptionModeHubBarPage.Base).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Bar).whenAtMode(page, Page.Description);

    public Setting<Boolean> descriptionModeHubBarGlow = setting("DesHubBarGlow", true).des("Description Hub Bar Glow").when(() -> descriptionMode.getValue() == DescriptionMode.Hub && descriptionModeHubBar.getValue()).whenAtMode(descriptionModeHubBarPage, DescriptionModeHubBarPage.Glow).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Bar).whenAtMode(page, Page.Description);
    public Setting<Float> descriptionModeHubBarGlowXOffset = setting("DesHubBarGlowX", 0.0f, -30.0f, 60.0f).des("Description Hub Bar Glow X Offset").whenTrue(descriptionModeHubBarGlow).when(() -> descriptionMode.getValue() == DescriptionMode.Hub && descriptionModeHubBar.getValue()).whenAtMode(descriptionModeHubBarPage, DescriptionModeHubBarPage.Glow).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Bar).whenAtMode(page, Page.Description);
    public Setting<Float> descriptionModeHubBarGlowYOffset = setting("DesHubBarGlowY", 0.0f, -40.0f, 40.0f).des("Description Hub Bar Glow Y Offset").whenTrue(descriptionModeHubBarGlow).when(() -> descriptionMode.getValue() == DescriptionMode.Hub && descriptionModeHubBar.getValue()).whenAtMode(descriptionModeHubBarPage, DescriptionModeHubBarPage.Glow).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Bar).whenAtMode(page, Page.Description);
    public Setting<Float> descriptionModeHubBarGlowWidth = setting("DesHubBarGlowWidth", 30.0f, 0.0f, 30.0f).des("Description Hub Bar Glow Width").whenTrue(descriptionModeHubBarGlow).when(() -> descriptionMode.getValue() == DescriptionMode.Hub && descriptionModeHubBar.getValue()).whenAtMode(descriptionModeHubBarPage, DescriptionModeHubBarPage.Glow).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Bar).whenAtMode(page, Page.Description);
    public Setting<Float> descriptionModeHubBarGlowHeight = setting("DesHubBarGlowHeight", 33.9f, 0.0f, 300.0f).des("Description Hub Bar Glow Height").whenTrue(descriptionModeHubBarGlow).when(() -> descriptionMode.getValue() == DescriptionMode.Hub && descriptionModeHubBar.getValue()).whenAtMode(descriptionModeHubBarPage, DescriptionModeHubBarPage.Glow).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Bar).whenAtMode(page, Page.Description);
    public Setting<Color> descriptionModeHubBarGlowColor = setting("DesHubBarGlowColor", new Color(new java.awt.Color(120, 40, 255, 100).getRGB())).des("Description Hub Bar Glow Color").whenTrue(descriptionModeHubBarGlow).when(() -> descriptionMode.getValue() == DescriptionMode.Hub && descriptionModeHubBar.getValue()).whenAtMode(descriptionModeHubBarPage, DescriptionModeHubBarPage.Glow).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Bar).whenAtMode(page, Page.Description);
    public Setting<Boolean> descriptionModeHubBarTextShadow = setting("DesHubBarTextShadow", true).des("Description hub bar text gradient shadow").whenTrue(descriptionModeHubHeaderText).when(() -> descriptionMode.getValue() == DescriptionMode.Hub && descriptionModeHubBar.getValue()).whenAtMode(descriptionModeHubBarPage, DescriptionModeHubBarPage.Glow).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Bar).whenAtMode(page, Page.Description);
    public Setting<Float> descriptionModeHubBarTextShadowWidth = setting("DesHubBarTextShadowWidth", -0.4f, -50.0f, 100.0f).des("Description hub bar text gradient shadow width").whenTrue(descriptionModeHubHeaderText).whenTrue(descriptionModeHubBarTextShadow).when(() -> descriptionMode.getValue() == DescriptionMode.Hub && descriptionModeHubBar.getValue()).whenAtMode(descriptionModeHubBarPage, DescriptionModeHubBarPage.Glow).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Bar).whenAtMode(page, Page.Description);
    public Setting<Float> descriptionModeHubBarTextShadowHeight = setting("DesHubBarTextShadowHeight", 0.9f, -50.0f, 50.0f).des("Description hub bar text gradient shadow height").whenTrue(descriptionModeHubHeaderText).whenTrue(descriptionModeHubBarTextShadow).when(() -> descriptionMode.getValue() == DescriptionMode.Hub && descriptionModeHubBar.getValue()).whenAtMode(descriptionModeHubBarPage, DescriptionModeHubBarPage.Glow).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Bar).whenAtMode(page, Page.Description);
    public Setting<Float> descriptionModeHubBarTextShadowSize = setting("DesHubBarTextShadowSize", 0.1f, 0.0f, 1.0f).des("Description hub bar text gradient shadow size").whenTrue(descriptionModeHubHeaderText).whenTrue(descriptionModeHubBarTextShadow).when(() -> descriptionMode.getValue() == DescriptionMode.Hub && descriptionModeHubBar.getValue()).whenAtMode(descriptionModeHubBarPage, DescriptionModeHubBarPage.Glow).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Bar).whenAtMode(page, Page.Description);
    public Setting<Integer> descriptionModeHubBarTextShadowAlpha = setting("DesHubBarTextShadowAlpha", 69, 0, 255).des("Description hub bar text gradient shadow alpha").whenTrue(descriptionModeHubHeaderText).whenTrue(descriptionModeHubBarTextShadow).when(() -> descriptionMode.getValue() == DescriptionMode.Hub && descriptionModeHubBar.getValue()).whenAtMode(descriptionModeHubBarPage, DescriptionModeHubBarPage.Glow).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Bar).whenAtMode(page, Page.Description);
    public Setting<Boolean> descriptionModeHubBarIconBG = setting("DesHubBarIconBG", true).des("Description hub bar icon background color block").whenTrue(descriptionModeHubIcon).when(() -> descriptionMode.getValue() == DescriptionMode.Hub && descriptionModeHubBar.getValue()).whenAtMode(descriptionModeHubBarPage, DescriptionModeHubBarPage.Glow).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Bar).whenAtMode(page, Page.Description);
    public Setting<Float> descriptionModeHubBarIconBGScaleOutside = setting("DesHubBarIconBGScale", 0.7f, 0.0f, 1.0f).des("Description hub bar icon background color block scale").whenTrue(descriptionModeHubIcon).whenTrue(descriptionModeHubBarIconBG).when(() -> descriptionMode.getValue() == DescriptionMode.Hub && descriptionModeHubBar.getValue()).whenAtMode(descriptionModeHubBarPage, DescriptionModeHubBarPage.Glow).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Bar).whenAtMode(page, Page.Description);
    public Setting<Float> descriptionModeHubBarIconBGSideX = setting("DesHubBarIconBGSideX", 0.0f, -30.0f, 30.0f).des("Description hub bar icon background color block side x offset").whenTrue(descriptionModeHubIcon).whenTrue(descriptionModeHubBarIconBG).when(() -> descriptionMode.getValue() == DescriptionMode.Hub && descriptionModeHubBar.getValue()).whenAtMode(descriptionModeHubBarPage, DescriptionModeHubBarPage.Glow).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Bar).whenAtMode(page, Page.Description);
    public Setting<Boolean> descriptionModeHubBarIconBGFade = setting("DesHubBarIconBGFade", true).des("Description hub bar icon background color block side fade").whenTrue(descriptionModeHubIcon).whenTrue(descriptionModeHubBarIconBG).when(() -> descriptionMode.getValue() == DescriptionMode.Hub && descriptionModeHubBar.getValue()).whenAtMode(descriptionModeHubBarPage, DescriptionModeHubBarPage.Glow).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Bar).whenAtMode(page, Page.Description);
    public Setting<Float> descriptionModeHubBarIconBGFadeSize = setting("DesHubBarIconBGFadeSize", 31.3f, -30.0f, 70.0f).des("Description hub bar icon background color block side fade size").whenTrue(descriptionModeHubIcon).whenTrue(descriptionModeHubBarIconBGFade).whenTrue(descriptionModeHubBarIconBG).when(() -> descriptionMode.getValue() == DescriptionMode.Hub && descriptionModeHubBar.getValue()).whenAtMode(descriptionModeHubBarPage, DescriptionModeHubBarPage.Glow).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Bar).whenAtMode(page, Page.Description);
    public Setting<Color> descriptionModeHubBarIconBGColor = setting("DesHubBarIconBGColor", new Color(new java.awt.Color(0, 0, 0, 93).getRGB())).des("Description hub bar icon background color block's color").whenTrue(descriptionModeHubIcon).whenTrue(descriptionModeHubBarIconBG).when(() -> descriptionMode.getValue() == DescriptionMode.Hub && descriptionModeHubBar.getValue()).whenAtMode(descriptionModeHubBarPage, DescriptionModeHubBarPage.Glow).whenAtMode(descriptionModeHubPage, DescriptionModeHubPage.Bar).whenAtMode(page, Page.Description);

    @Override
    public void onDisable() {
        enable();
    }

    enum Page {
        Description
    }

    public enum DescriptionMode {
        MouseTag, Hub
    }

    public enum DescriptionModeHubPage {
        Text, Rect, Outline, Bar, Shadow, RectInGlow
    }

    public enum DescriptionModeHubDesTextFont {
        Comfortaa, Arial, Objectivity, Minecraft
    }

    public enum DescriptionModeHubBarPage {
        Base, Glow, Outline
    }
}
